/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyFinalAtencionResto.Vistas;

import java.awt.BorderLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import proyFinalAtencionResto.AccesoADatos.MesaData;
import proyFinalAtencionResto.AccesoADatos.MeseroData;
import proyFinalAtencionResto.AccesoADatos.PedidoData;
import proyFinalAtencionResto.Entidades.Mesa;
import proyFinalAtencionResto.Entidades.Mesero;
import proyFinalAtencionResto.Entidades.Pedido;
import static proyFinalAtencionResto.Vistas.MetodoDePago.jlMonto;
import static proyFinalAtencionResto.Vistas.PagoConEfectivo.jlMonto1;


/**
 *
 * @author Asus
 */
public class CobranzaDePedido extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo = new DefaultTableModel();
    public static double importeTotal = 0;
//    JInternalFrame escritorio = new JInternalFrame();
    
    
    /**
     * Creates new form CobranzaDePedido
     */
    public CobranzaDePedido() {
        initComponents();
        cargarCombo();
        armarCabecera();
//        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioCobranza = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jlMesero = new javax.swing.JLabel();
        jlMesa = new javax.swing.JLabel();
        jcbMesa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbAnular = new javax.swing.JButton();
        jbCobrar = new javax.swing.JButton();
        jcbMesero = new javax.swing.JComboBox();
        jbCargar = new javax.swing.JButton();

        setTitle("COBRANZA DE PEDIDOS");

        jlMesero.setText("Mesero");

        jlMesa.setText("Mesa");

        jcbMesa.setToolTipText("");
        jcbMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesaActionPerformed(evt);
            }
        });

        jtPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPedido);

        jLabel1.setText("Seleccione los pedidos pendientes que desea cobrar");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbAnular.setText("Nueva consulta");
        jbAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularActionPerformed(evt);
            }
        });

        jbCobrar.setText("Cobrar");
        jbCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCobrarActionPerformed(evt);
            }
        });

        jcbMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMeseroActionPerformed(evt);
            }
        });

        jbCargar.setText("Cargar");
        jbCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jbCobrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbAnular)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlMesa)
                                        .addComponent(jlMesero))
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbMesero, 0, 120, Short.MAX_VALUE)
                                        .addComponent(jcbMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbCargar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMesero)
                            .addComponent(jcbMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMesa)
                            .addComponent(jcbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAnular)
                    .addComponent(jbCobrar)
                    .addComponent(jbSalir)))
        );

        escritorioCobranza.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioCobranzaLayout = new javax.swing.GroupLayout(escritorioCobranza);
        escritorioCobranza.setLayout(escritorioCobranzaLayout);
        escritorioCobranzaLayout.setHorizontalGroup(
            escritorioCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioCobranzaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        escritorioCobranzaLayout.setVerticalGroup(
            escritorioCobranzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioCobranzaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioCobranza)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioCobranza)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < jtPedido.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        }
        jbCargar.setEnabled(true);
        
    }//GEN-LAST:event_jbAnularActionPerformed

    private void jbCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCobrarActionPerformed
        // TODO add your handling code here:
//        PanelPrincipal.escritorio.repaint();
        jPanel1.setVisible(false);MetodoDePago mp = new MetodoDePago();
        escritorioCobranza.add(mp);
        escritorioCobranza.moveToFront(mp);
//        mp.setLocation(0, 0);
        mp.setVisible(true);
        escritorioCobranza.setSize(550, 379);
        
//        jPanel1.setVisible(false);
//        jPanel1.removeAll();
//        jPanel1.add(mp, BorderLayout.CENTER);
//        jPanel1.revalidate();
//        mp.setLocation(0, 0);
//        mp.setSize(700, 600);
       
//        jPanel1.repaint();
        
       
//        this.dispose();
        ArrayList<Double> importes = new ArrayList<>();
        int largo = jtPedido.getSelectedRowCount();
        int[] filasSelecionadas = new int[largo];
        filasSelecionadas = jtPedido.getSelectedRows();
        for (int i: filasSelecionadas) {
            importes.add((Double) jtPedido.getValueAt(i, 2));
        }
        int i = 0;
        for (double importe: importes) {
            importeTotal = importeTotal+ importes.get(i);
            i = i+1;
        }
        DecimalFormat df = new DecimalFormat("###.##");
        jlMonto.setText(df.format(importeTotal));
//        System.out.println(df.format(importeTotal));
        
//        filas = 
//        System.out.println(filas);
//        for (int i: filas) {
//            importes.add((Double) jtPedido.getValueAt(i, 2));
//        }
//        for (int i: filas) {
//            importeTotal = importeTotal + importes.get(i);
//        }
//        System.out.println(importeTotal);
//        for (int i: filas) {
//            importeTotal = importeTotal+(Double)jtPedido.getValueAt(i, 2);
//        }
        
    }//GEN-LAST:event_jbCobrarActionPerformed

    private void jcbMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMeseroActionPerformed
        // TODO add your handling code here:
        jcbMesa.removeAllItems();
        Mesero meseroSeleccionado = new Mesero();
        meseroSeleccionado = (Mesero)jcbMesero.getSelectedItem();
        PedidoData pd = new PedidoData();
        List<Mesa> mesas = new ArrayList<>();
        mesas = pd.listarMesasPorIdMesero(meseroSeleccionado.getIdMesero());
        for (Mesa mesa: mesas) {
            jcbMesa.addItem(mesa);
        }
    }//GEN-LAST:event_jcbMeseroActionPerformed

    private void jcbMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jcbMesaActionPerformed

    private void jbCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarActionPerformed
        // TODO add your handling code here:
        
        PedidoData pd = new PedidoData();
        List<Pedido> pedidos = new ArrayList<>();
        Mesero mesero = (Mesero)jcbMesero.getSelectedItem();
        Mesa mesa = (Mesa) jcbMesa.getSelectedItem();
        pedidos = pd.listarPedidosPorIdMeseroIdMesa(mesero.getIdMesero(),mesa.getIdMesa());
        for (Pedido pedido: pedidos) {
            modelo.addRow(new Object[]{pedido.getIdPedido(), pedido.getFechaHora(), pedido.getImporte(), pedido.isCobrado()});
        }
        jbCargar.setEnabled(false);
    }//GEN-LAST:event_jbCargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioCobranza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnular;
    private javax.swing.JButton jbCargar;
    private javax.swing.JButton jbCobrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Mesa> jcbMesa;
    private javax.swing.JComboBox jcbMesero;
    private javax.swing.JLabel jlMesa;
    private javax.swing.JLabel jlMesero;
    private javax.swing.JTable jtPedido;
    // End of variables declaration//GEN-END:variables

private void cargarCombo() {
        MeseroData ms = new MeseroData();
        List<Mesero> meseros = new ArrayList<>();
        meseros = ms.listaDeMeseros();
        for (Mesero mesero: meseros) {
            jcbMesero.addItem(mesero);
        }
    
    }
    
    private void armarCabecera() {
        modelo.addColumn("Pedido");
        modelo.addColumn("Fecha");
        modelo.addColumn("Importe");
        modelo.addColumn("Cobrado");
        jtPedido.setModel(modelo);
    }
    
    
    

}
