/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyFinalAtencionResto.Vistas;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyFinalAtencionResto.AccesoADatos.PedidoData;
import proyFinalAtencionResto.AccesoADatos.PedidoProductoData;
import proyFinalAtencionResto.Entidades.Mesero;
import proyFinalAtencionResto.Entidades.Pedido;
import proyFinalAtencionResto.Entidades.Producto;

/**
 *
 * @author eduardo
 */
public class ConsultasdePedidos extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){
        if ((columna==1) & (columna==2)){
            return true;
        }else{
            return false;
        }
    }
};
    private ArrayList<Producto> productosPedidos = new ArrayList();
    private Mesero mesero = null;
    private Producto producto=null;
    private int nroMesa;
    private int nroMozo;
    private final double IVA = 0.21; 
    private double subtotal=0;
    private double total=0;
    private PedidoData pedidoData = new PedidoData();
    private PedidoProductoData pedidoproductoData = new PedidoProductoData();
    private String fechaABuscar;
    private  int pedidoSeleccionado;
    /**
     * Creates new form AltaPedido
     */
    public ConsultasdePedidos() {
        initComponents();
         this.setSize(1150, 650);
         this.setLocation(5,5);
        armarCabecera();
        jFecha.setEnabled(false);
        jbOtraConsulta.setEnabled(false);
        jbBuscar1.setEnabled(false);
        jtPedido.setEditable(false);
        buttonGroup.add(jrPorFecha);
        buttonGroup.add(jrPorNro);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jpanelDeArriba = new javax.swing.JPanel();
        jlFecha = new javax.swing.JLabel();
        jFecha = new com.toedter.calendar.JDateChooser();
        jlFecha1 = new javax.swing.JLabel();
        jtPedido = new javax.swing.JTextField();
        jrPorFecha = new javax.swing.JRadioButton();
        jrPorNro = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jbBuscar1 = new javax.swing.JButton();
        jpanelDeAbajjo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtItems = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jbOtraConsulta = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 0));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONSULTAS DE PEDIDOS");

        jpanelDeArriba.setBackground(new java.awt.Color(255, 0, 0));
        jpanelDeArriba.setAutoscrolls(true);

        jlFecha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jlFecha.setText("Nro de pedido:");

        jFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFechaPropertyChange(evt);
            }
        });

        jlFecha1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jlFecha1.setText("Fecha:");

        jrPorFecha.setText("Consultar por fecha");
        jrPorFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrPorFechaMouseClicked(evt);
            }
        });

        jrPorNro.setText("Consultar por numero");
        jrPorNro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrPorNroMouseClicked(evt);
            }
        });

        jLabel1.setText("Marque la opcion deseada:");

        jbBuscar1.setText("Consultar");
        jbBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelDeArribaLayout = new javax.swing.GroupLayout(jpanelDeArriba);
        jpanelDeArriba.setLayout(jpanelDeArribaLayout);
        jpanelDeArribaLayout.setHorizontalGroup(
            jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrPorNro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrPorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
            .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                        .addComponent(jlFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                        .addComponent(jlFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(232, 232, 232)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                    .addGap(261, 261, 261)
                    .addComponent(jbBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
        );
        jpanelDeArribaLayout.setVerticalGroup(
            jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jrPorFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrPorNro))
                    .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                        .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelDeArribaLayout.createSequentialGroup()
                                .addComponent(jFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jpanelDeArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelDeArribaLayout.createSequentialGroup()
                    .addContainerGap(109, Short.MAX_VALUE)
                    .addComponent(jbBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jpanelDeAbajjo.setBackground(new java.awt.Color(0, 204, 51));
        jpanelDeAbajjo.setAutoscrolls(true);

        jtItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtItems);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbOtraConsulta.setText("Otra Consulta");
        jbOtraConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOtraConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelDeAbajjoLayout = new javax.swing.GroupLayout(jpanelDeAbajjo);
        jpanelDeAbajjo.setLayout(jpanelDeAbajjoLayout);
        jpanelDeAbajjoLayout.setHorizontalGroup(
            jpanelDeAbajjoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDeAbajjoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelDeAbajjoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelDeAbajjoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelDeAbajjoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbOtraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jpanelDeAbajjoLayout.setVerticalGroup(
            jpanelDeAbajjoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDeAbajjoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jpanelDeAbajjoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOtraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelDeArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jpanelDeAbajjo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelDeArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpanelDeAbajjo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFechaPropertyChange
           
        if(jFecha.getDate()!=null){
            LocalDateTime fechanueva = jFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            fechaABuscar= fechanueva.format(dtf);
        }
    }//GEN-LAST:event_jFechaPropertyChange

    private void jbOtraConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOtraConsultaActionPerformed
        borrarFilas();
         jFecha.setEnabled(false);
        jbOtraConsulta.setEnabled(true);
        jtPedido.setEditable(false);
        jtPedido.setText("");
     jbBuscar1.setEnabled(false);
        

    }//GEN-LAST:event_jbOtraConsultaActionPerformed

    private void jtItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtItemsMouseClicked
       int filaSeleccionada = jtItems.getSelectedRow();
         if(filaSeleccionada!=-1){
            pedidoSeleccionado=(Integer) jtItems.getValueAt(filaSeleccionada, 0);
    }//GEN-LAST:event_jtItemsMouseClicked
    }
    
    
    
    private void jrPorFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrPorFechaMouseClicked
    
     jFecha.setEnabled(true);
     jbOtraConsulta.setEnabled(true);
     jtPedido.setEditable(false);
     jrPorNro.setSelected(false);
     jtPedido.setText("");
     jbOtraConsulta.setEnabled(true);
     jbBuscar1.setEnabled(true);
     
      
     
    }//GEN-LAST:event_jrPorFechaMouseClicked

    private void jrPorNroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrPorNroMouseClicked
     jFecha.setEnabled(false);
     jbOtraConsulta.setEnabled(true);
     jtPedido.setEditable(true);
     jrPorFecha.setSelected(false);
          jbOtraConsulta.setEnabled(true);
     jbBuscar1.setEnabled(true);

        
    }//GEN-LAST:event_jrPorNroMouseClicked

    private void jbBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscar1ActionPerformed
        try{
        borrarFilas();
        if(jrPorFecha.isSelected()){
        cargarTablaPedidos(fechaABuscar);
        }else{
            if(jtPedido.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "el campo del numero de pedido no puede estar vacio");
                return;
            }
            else{
          
            cargarTablaPedidoporNumero(Integer.parseInt(jtPedido.getText()));
                    }
        }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de pedido, controle lo que ingreso");
        }
            
        
    }//GEN-LAST:event_jbBuscar1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private com.toedter.calendar.JDateChooser jFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar1;
    private javax.swing.JButton jbOtraConsulta;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlFecha1;
    private javax.swing.JPanel jpanelDeAbajjo;
    private javax.swing.JPanel jpanelDeArriba;
    private javax.swing.JRadioButton jrPorFecha;
    private javax.swing.JRadioButton jrPorNro;
    private javax.swing.JTable jtItems;
    private javax.swing.JTextField jtPedido;
    // End of variables declaration//GEN-END:variables

private void cargarComboBoxMesero(){
  mesero=new Mesero();
  mesero.setIdMesero(1);
  mesero.setNombre("Donald");
  mesero.setApellido("Trump");
  mesero.setDni(17656789);
  mesero.setDomicilio("Lacarra 2345");
  mesero.setLocalidad("Avellaneda");
  mesero.setTelefono("011 4566 - 7889");
  mesero.setProvincia("Buenos Aires");
  Mesero mesero1=new Mesero();
  mesero1.setIdMesero(2);
  mesero1.setNombre("Marcelo");
  mesero1.setApellido("Tinelli");
  mesero1.setDni(17656789);
  mesero1.setDomicilio("Lacarra 2345");
  mesero1.setLocalidad("Avellaneda");
  mesero1.setTelefono("011 4566 - 7889");
  mesero1.setProvincia("Buenos Aires");
//  jcbLegajo.addItem(mesero.getIdMesero());
//  jcbLegajo.addItem(mesero1.getIdMesero());
// 
  
//    List<Alumno> alumnos = aluData.listarAlumnos();
//     for (Alumno alu : alumnos){
//        jcbAlumno.addItem(alu);
//     }
}

 private void armarCabecera(){
        
        CabeceraTablaBajaPedido[] tope = CabeceraTablaBajaPedido.values();
      
        for (int i=0;i<tope.length;i++){
            modelo.addColumn(tope[i]);
            
        }
        
        jtItems.setModel(modelo);
        
        
        
    }
 
 
 
 
 
 
 //**** cargar la tabla *******
 
    private void cargarTablaPedidos(String fechaRecibida){
        List<Pedido> pedidos = new ArrayList();
        pedidos=pedidoData.listarPedido(fechaRecibida);
        for (Pedido ped : pedidos) {
        Object vector[]= new Object[4];
                vector[0]=ped.getIdPedido();
                vector[1]=ped.getIdMesero();
                vector[2]=ped.getIdMesa();
                vector[3]=ped.getImporte();
                modelo.addRow(vector);
        }
        
    }
 
    private void  cargarTablaPedidoporNumero(int pedidoAConsultar){
        List<Pedido> pedidos = new ArrayList();
        pedidos=pedidoData.listarPedidoporNumero(pedidoAConsultar);
        for (Pedido ped : pedidos) {
        Object vector[]= new Object[4];
                vector[0]=ped.getIdPedido();
                vector[1]=ped.getIdMesero();
                vector[2]=ped.getIdMesa();
                vector[3]=ped.getImporte();
                modelo.addRow(vector);
        }
        
    }
    
    
 
 

    private void borrarFilas(){
        
        int fila=jtItems.getRowCount()-1;
        for (; fila>=0; fila--) {
            modelo.removeRow(fila);
        }
        
   
        
        
    }

       
}
